### PR TITLE
Fix upward scroll system flickering

### PR DESCRIPTION
**Pull request by cryptoethic**
@petyosi  I think I got it.

So the problem with #418 was that u.scan subsystem from upwardScrollFixSystem was executing only when scrolling upwards, therefore items that were expanded while scrolling down had incorrect sizes and offsets in prevItems array.

This solution replaces execution order.

Please review this PR ;)

### CODE REVIEW

**Comment by petyosi** [comment]
That's a good catch, seems plausible. I will take a look

**Comment by cryptoethic** [comment]
Thanks! I know you have a lot of work in your pipeline but if you could take a look soon I would be very grateful. This issue is blocking for our release and we would like to get it fixed as soon as possible.

If it is not a solution we would like to focus our time for finding it as soon as possible ;-)

**Comment by petyosi** [comment]
So far this looks very very correct. I just need to double-check before I merge. If this is blocking your release, I may recommend you use your fork for this purpose.

**Comment by cryptoethic** [comment]
I had a problem when installing fork as npm module and getting a code review might be important as I don't want to introduce new issues ;)

Take your time!

**Comment by petyosi** [comment]
Congrats, I would say that you are the 2nd person apart from me who has done a non-trivial change in the urx-based core of the project :).

**Comment by cryptoethic** [comment]
Thanks for your help during this issue! Without it I would be nowhere near.

It seems like scroll flickering problem is solved. What's more I got some basic knowledge about urx system that is behind react-virtuoso and as I said before - I'm quite impressed!

Let me know in case you would need any help in the future ;)

**Pull request merged**
